### ISSUE TITLE
How to import Bootstrap 4 js files for use with Partytown

### ISSUE THREAD

**Issue by munchkindev** [BuilderIO/partytown#258]
In the following function:
```
function setTransitionEndSupport() {
  $.fn.emulateTransitionEnd = transitionEndEmulator
  $.event.special[Util.TRANSITION_END] = getSpecialTransitionEndEvent()
}
```
on line 2 I get an error stating `util.js:55 Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
    at setTransitionEndSupport (util.js:55:5)
    at util.js:175:1
    at bootstrap.js:9:29
    at bootstrap.js:10:2`

I'm trying to import and forward Bootstrap 4. My config looks like the following:
```
<script>
    partytown = {
      forward: ['dataLayer.push', 'setTransitionEndSupport', 'transitionEndEmulator', '$.fn.emulateTransitionEnd', '$', '$.fn.emulateTransitionEnd.push', 'getSpecialTransitionEndEvent', '$.event.special[Util.TRANSITION_END]'],
    };
  </script>
```

I inputted a lot of events etc because I don't know which one is actually required, so this was the way to go for me.

Help is much appreciated.

**Comment by munchkindev** [comment]
Now I'm getting 
```
util.js:55 Uncaught TypeError: Cannot read properties of undefined (reading 'fn')
    at setTransitionEndSupport (util.js:55:5)
    at util.js:175:1
    at bootstrap.js:9:29
    at bootstrap.js:10:2
```

and
```
TypeError: Cannot read properties of undefined (reading 'hover')
    at Proxy.eval (site.js?v=IrIIqQAYEaC_20EfdHE7yp6-xBs5KmdlWDzmoCWFyf0:8:15)
    at run (partytown-ww-sw.js?v=0.7.0-dev1663849013287:873:37)
    at partytown-ww-sw.js?v=0.7.0-dev1663849013287:1952:33
```
...where the hover function attaches to an jQuery selector.

**Comment by adamdbradley** [comment]
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.
