### ISSUE TITLE
Need working example for Google Publisher Tag

### ISSUE THREAD

**Issue by pm-harshad-mane** [BuilderIO/partytown#350]
**Is your feature request related to a problem? Please describe.**
I am new here, and I am having hard time making my simple test page work with Partytown.

**Describe the solution you'd like**
A sample config or the code change suggestions in the below example

**Describe alternatives you've considered**
I tried below config but it did not work, i always get error `googletag not defined`

**Additional context**
I am sharing the original source code of the page where i would like to use `gpt.js` and the last `script tag` with Partytown.

```
<!DOCTYPE html>
<html>
<head>
	<title>Parttown Example with Google Publisher Tag</title>	
</head>
<body>
	<div id="output"></div>
	<script  async src="//www.googletagservices.com/tag/js/gpt.js"></script>
    <script type="text/javascript">
    	var googletag = googletag || {};
        googletag.cmd = googletag.cmd || [];

		googletag.cmd.push(function() {
		    googletag.pubads().disableInitialLoad();
		});
		var div_1_sizes = [
		    [300, 250],
		    [300, 600]
		];
		var div_2_sizes = [
		    [728, 90],
		    [970, 250]
		];

		googletag.cmd.push(function() {
		    googletag.defineSlot('/19968336/header-bid-tag-0', div_1_sizes, 'div-1').addService(
		    	googletag.pubads()
		    );
		    googletag.pubads().enableSingleRequest();
            googletag.enableServices();
            googletag.display('div-1');
		});

		googletag.cmd.push(function() {
		    googletag.defineSlot('/19968336/header-bid-tag-1', div_2_sizes, 'div-2').addService(
		    	googletag.pubads()
		    );
		    googletag.pubads().enableSingleRequest();
            googletag.enableServices();            
            googletag.display('div-2');
		});

		setTimeout(function() {
		    googletag.cmd.push(function() {
                googletag.pubads().refresh();
            });
		}, 3000);		
    </script>

    <h2>Basic Prebid.js Example</h2>
    <h5>Div-1</h5>
    <div id='div-1'></div>
    <br>
    <h5>Div-2</h5>
    <div id='div-2'></div>
</body>
</html>
```

**Comment by pm-harshad-mane** [comment]
Hi @vip30 were you able to set up Google Publisher Tag with Partytown?

**Comment by vip30** [comment]
https://replit.com/@vip301/Google-Publisher-Tag-Partytown-Example
here is the example of google publisher but I have no idea how to forward `googletag.defineSlot('/19968336/header-bid-tag-1', div_2_sizes, 'div-2').addService`

**Comment by pm-harshad-mane** [comment]
Thanks @vip30 , i am also stuck with this error.

**Comment by pm-harshad-mane** [comment]
@adamdbradley can you help us with a working example? will be a great help to a wider audience as GPT is integrated into almost all publisher websites for serving ads.

**Comment by Girilloid** [comment]
@vip30, thanks for mentioning my PR, but unfortunately it will not help with your issue.
The thing is that you are expecting to retrieve an object with some methods implementend, but actually return value of forwarded call will be transfered back to main thread via `postMessage`. MDN says that: 
```
The data may be any value or JavaScript object handled by the structured clone algorithm, which includes cyclical references.
```
It means that you will be able to only receive plain objects in return (if it will not throw error as `structuredClone` does).

**Comment by vip30** [comment]
@Girilloid thanks for your reply

do you mean to create a function in the worker thread for handling the such cases?

something like

```
window.customPubAds = () => {
		googletag.cmd.push(function() {
		    googletag.pubads().disableInitialLoad();
		});
}
```

**Comment by Girilloid** [comment]
@vip30, yep, exactly. For sure it will not be as flexible as it can be, but at least you can manage to get it working inside sandbox.

**Comment by dagrinchi** [comment]
Good morning guys, have you any luck on this? 

I created a proxy server like the docs say and the problem of CORS is solved.

But now I have this issue with https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202310240101/pubads_impl.js It seems it is trying to reach the variable window.document.scripts from the worker.

Any advice?

Bests regards

Here is the error:
Uncaught TypeError: Cannot read properties of undefined (reading 'length') at eval (pubads_impl.js:20:24133)

**Comment by radiantstatic** [comment]
> Good morning guys, have you any luck on this?
> 
> I created a proxy server like the docs say and the problem of CORS is solved.
> 
> But now I have this issue with https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202310240101/pubads_impl.js It seems it is trying to reach the variable window.document.scripts from the worker.
> 
> Any advice?
> 
> Bests regards
> 
> Here is the error: Uncaught TypeError: Cannot read properties of undefined (reading 'length') at eval (pubads_impl.js:20:24133)

I am currently facing the same issue - any help would be much appreciated.
