### ISSUE TITLE
[🐞] Error: TypeError: Failed to execute 'insertAdjacentElement' on 'Element

### ISSUE THREAD

**Issue by venkatnarasimharao** [BuilderIO/partytown#413]
### Describe the bug

I am trying to use partytown for cookielaw by following the steps mentioned in official website 
  
  <script src="/~partytown/debug/partytown.js"></script>
script type="text/javascript" replaced with type="text/partytown"

It throws errors 
1. Uncaught (in promise) Error: TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'.
    at applyToInstance (partytown-sandbox-sw.js:264:59)

2. partytown-ww-sw.js?v=0.8.0:1767 TypeError: Cannot read properties of undefined (reading 'registerPlugin')
    at eval (videojs-transcript-click.min.js:9:5285)
    at Proxy.eval (videojs-transcript-click.min.js:9:5910)
    at run (partytown-ww-sw.js?v=0.8.0:703:37)
    at partytown-ww-sw.js?v=0.8.0:1759:37

3. partytown-ww-sw.js?v=0.8.0:1767 TypeError: Cannot read properties of undefined (reading 'getComponent')
    at eval (videojs-seek-buttons.min.js:4:316)
    at eval (videojs-seek-buttons.min.js:4:199)
    at Proxy.eval (videojs-seek-buttons.min.js:4:212)
    at run (partytown-ww-sw.js?v=0.8.0:703:37)
    at partytown-ww-sw.js?v=0.8.0:1759:37

### Reproduction

cookielaw

### Steps to reproduce

  
<script src="cndOfcookielaw"  type="text/partytown" charset="UTF-8" data-domain-script="id" ></script>

### Browser Info

Chrome

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing test in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.
